spring:
  application:
    name: eurekaclient
server:
  port: 2006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
# 暴漏全部的服务监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always # 显示健康状况详细信息
  info:
    git:
      mode: simple # full 在/actuator/info中显示git详细信息  simple 在/actuator/info中显示git简略信息
# /actuator/info 自定义的info端点 否则是空的
info:
  app:
    version: 1.1.1.1.1 多点看起来厉害些
    name: eurekaclient
    size: 可能有100M吧
  date:
    create: 2018-01-01
    online_time: 3018-01-01
    ...: ...